// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqpzssufjevwmiwssqgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxcHpzc3VmamV2d21pd3NzcWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMzkwMDUsImV4cCI6MjA1NDkxNTAwNX0.1zC3PUuWt1cohnCZ2xE0UsBY5Pd1-2xd3gAuC7KAnHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);